### ISSUE TITLE
RubyDNS 0.6.0 chnges.

### ISSUE THREAD

**Issue by ioquatix** [narkisr-deprecated/vagrant-dns-server#1]
Hi,

RubyDNS 0.6.0 has ONE backwards incompatible change. The order of arguments for pattern based rules has changed.

Previously:

```
match(/pattern/, ...) do |match_data, transaction|
end
```

Now:

```
match(/pattern/, ...) do |transaction, match_data|
end
```

The motivation for this change is that `match_data` is often not needed, so now can be dropped from the argument list all together:

```
match(/pattern/, ...) do |transaction|
end
```

Let me know if you have any questions.

**Comment by narkisr** [comment]
Hey Samuel, thank you for heads up ill fix that, the change does make sense

**Comment by narkisr** [comment]
Hey Samuel from what iv seen I don't use match at all so nothing to migrate accept updating gem versions :)

v0.3 uses the lates rubydns (0.6.0) 

Cheers
Ronen
